apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-configmap
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete,pre-rollback
data:
  env: |
      ######### k8s #########
      HELM_VERSION="{{ .Release.Name | printf "%s-%s" .Chart.Name }} in {{ .Release.Namespace }} namespace and chart version is {{ .Chart.Version }}."
      RELEASE_NAME={{ .Release.Name }}
      CHART_NAME={{ .Chart.Name }}
      RELEASE_NAMESPACE={{ .Release.Namespace }}
      CHART_VERSION={{ .Chart.Version }}

      APP_NAME={{ .Values.envFile.APP_NAME }}
      APP_ENV={{ .Values.envFile.APP_ENV }}
      APP_KEY={{ .Values.envFile.APP_KEY }}
      APP_DEBUG={{ default "false" .Values.envFile.APP_DEBUG }}
      APP_URL={{ default "http://localhost" .Values.envFile.APP_URL }}
      ASSET_URL={{ default "http://localhost" .Values.envFile.APP_URL }}

      LOG_CHANNEL={{ default "stderr" .Values.envFile.LOG_CHANNEL }}

      AUTHOR={{ default "duc" .Values.envFile.AUTHOR }}

      ####### mysql #######
      DB_CONNECTION={{ default "mysql" .Values.envFile.DB_CONNECTION }}
      # DB_HOST: "127.0.0.1"
      # DB_PORT: "3306"
      # DB_DATABASE: laravel
      # DB_USERNAME: root
      # DB_PASSWORD: 

      DUC_NAME={{ default "1234567" .Values.envFile.DUC_NAME }}

      BROADCAST_DRIVER={{ default "log" .Values.envFile.BROADCAST_DRIVER }}
      CACHE_DRIVER={{ default "file" .Values.envFile.CACHE_DRIVER }}
      QUEUE_CONNECTION={{ default "sync" .Values.envFile.QUEUE_CONNECTION }}
      SESSION_DRIVER={{ default "file" .Values.envFile.SESSION_DRIVER }}
      SESSION_LIFETIME={{ default "120" .Values.envFile.SESSION_LIFETIME }}

      ####### redis #######
      {{ if .Values.envFile.REDIS_HOST }}
        REDIS_HOST={{ .Values.envFile.REDIS_HOST }}
      {{ else }}
        REDIS_HOST={{ .Release.Name }}-redis-master
      {{ end }}
      REDIS_PASSWORD={{ default "null" .Values.envFile.REDIS_PASSWORD }}
      REDIS_PORT={{ default "6379" .Values.envFile.REDIS_PORT }}

      MAIL_MAILER={{ default "smtp" .Values.envFile.MAIL_MAILER }}
      MAIL_HOST={{ default "smtp.mailtrap.io" .Values.envFile.MAIL_HOST }}
      MAIL_PORT={{ default "2525" .Values.envFile.MAIL_PORT }}
      MAIL_USERNAME={{ default "null" .Values.envFile.MAIL_USERNAME }}
      MAIL_PASSWORD={{ default "null" .Values.envFile.MAIL_PASSWORD }}
      MAIL_ENCRYPTION={{ default "null" .Values.envFile.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS={{ default "null" .Values.envFile.MAIL_FROM_ADDRESS }}
      MAIL_FROM_NAME={{ default .Values.envFile.APP_NAME .Values.envFile.MAIL_FROM_NAME }}

      AWS_ACCESS_KEY_ID={{ .Values.envFile.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY={{ .Values.envFile.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION={{ default "us-east-1" .Values.envFile.AWS_DEFAULT_REGION }}
      AWS_BUCKET={{ .Values.envFile.AWS_BUCKET }}

      PUSHER_APP_ID={{ .Values.envFile.PUSHER_APP_ID }}
      PUSHER_APP_KEY={{ .Values.envFile.PUSHER_APP_KEY }}
      PUSHER_APP_SECRET={{ .Values.envFile.PUSHER_APP_SECRET }}
      PUSHER_APP_CLUSTER={{ default "mt1" .Values.envFile.PUSHER_APP_CLUSTER }}

      MIX_PUSHER_APP_KEY={{ default .Values.envFile.PUSHER_APP_KEY .Values.envFile.MIX_PUSHER_APP_KEY }}
      MIX_PUSHER_APP_CLUSTER={{ default .Values.envFile.PUSHER_APP_CLUSTER .Values.envFile.MIX_PUSHER_APP_CLUSTER }}

  nginx.conf: |
      server {
          listen 80;
          
          root /var/www/html/public;

          index index.html index.php index.htm index.nginx-debian.html;

          client_max_body_size 20M;

          location / {
              try_files $uri $uri/ /index.php$is_args$args;
          }

          location ~ \.php$ {
            fastcgi_pass   localhost:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
          }
      }