{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "laravel-workflow.fullname" . }}
  labels:
    {{- include "laravel-workflow.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: schedulerun
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            args:
            - su - www-data
            - -c
            - "/usr/local/bin/php ./artisan schedule:run"
          restartPolicy: OnFailure
{{- end }}
