{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-{{ include "laravel-workflow.fullname" . }}
  labels:
    {{- include "laravel-workflow.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: laravel-env
            configMap:
              name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-configmap
              items: 
                - key: env
                  path: .env
          containers:
          - name: schedulerun
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            # TODO 这里需要用 www-data 的身份来执行定时任务，不然如果任务有写文件操作会报错
            args:
            - /usr/local/bin/php 
            - /var/www/html/artisan 
            - schedule:run
          restartPolicy: OnFailure
          volumeMounts:
            - name: laravel-env
              mountPath: /var/www/html/.env
              subPath: .env
{{- end }}
