apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-workflow.fullname" . }}
  labels:
    {{- include "laravel-workflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "laravel-workflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laravel-workflow.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: laravel-env
          configMap:
            name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
            items: 
              - key: env
                path: .env
    {{- with .Values.staticAssetsMountPath }}
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: gitclone
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
          - name: shared-data
            mountPath: {{ .Values.staticAssetsMountPath }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "laravel-workflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
              - name: nginx
          image: "nginx: {{ .Values.nginx.tag }}"
        {{- with .Values.staticAssetsMountPath }}
          volumeMounts:
            - name: laravel-env
              mountPath: /var/www/html/.env
              subPath: .env
        {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
