apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-workflow.fullname" . }}
  labels:
    {{- include "laravel-workflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.service.nodePort }}
    {{ if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
    {{ end }}
    {{ end }}
  selector:
    {{- include "laravel-workflow.selectorLabels" . | nindent 4 }}
